package PuntoVenta.Ventanas;

import Administrador.Ventanas.Admin;
import PuntoVenta.BaseDatos.Empleado;
import PuntoVenta.Inicio.MenuPrincipal;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import PuntoVenta.BaseDatos.ObjetoBaseDatos;
import javax.swing.JOptionPane;

public class ClaveSuperUsuario extends javax.swing.JDialog {
//    private Admin admin;
    public final MenuPrincipal menuPrincipal;
    private final ObjetoBaseDatos obd;
    
    public ClaveSuperUsuario(java.awt.Frame parent, boolean modal, MenuPrincipal menuPrincipal) {
        super(parent, modal);
        initComponents();
        centrar(this);
        this.menuPrincipal = menuPrincipal;
        this.obd = menuPrincipal.getOBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpwClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpwClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpwClaveKeyTyped(evt);
            }
        });

        jLabel1.setText("contraseña de administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpwClave, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jpwClave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpwClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwClaveKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)  autenticarClave(false);
    }//GEN-LAST:event_jpwClaveKeyTyped
    
    public boolean autenticarClave(boolean desdeAfuera) {
        char[] pass = jpwClave.getPassword();
        Empleado emple = this.obd.getDatosEmpleadoClave(pass);
  
        if(emple.getCargo_id() != null) {
            this.dispose();
            return true;
        } else {
            if(!desdeAfuera) {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                jpwClave.setText("");
            }
            return false;
        }
    }
    // centra la ventana
    public void centrar(JDialog esto) {
        Rectangle abounds = esto.getBounds();
        esto.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - abounds.width) / 2, 
                ((Toolkit.getDefaultToolkit().getScreenSize().height - abounds.height) / 2) - 30);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jpwClave;
    // End of variables declaration//GEN-END:variables
}
