/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PuntoVenta.Ventanas;

import PuntoVenta.Inicio.MenuPrincipal;
import ClasesExtendidas.Tablas.ArrayListTableModel;
import ClasesExtendidas.Tablas.MovimientoTableModel;
import PuntoVenta.BaseDatos.ObjetoBaseDatos;
import PuntoVenta.Modelos.ModeloProducto;
import PuntoVenta.Ventanas.Compra;
import PuntoVenta.Ventanas.Fabricacion;
import PuntoVenta.Ventanas.Ajuste;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author David Chavez
 */
public class Movimientos extends javax.swing.JInternalFrame {

private Modulo ventanaAbierta;    
public MenuPrincipal menuPrincipal;
public Compra compra;
public Fabricacion fabricacion;
public Ajuste ajuste;
public Reporte reporte;

    /**
     * Creates new form Productos
     */
    public Movimientos(MenuPrincipal menuPrincipal) {
       initComponents();
       this.menuPrincipal = menuPrincipal;
       this.ajuste = new Ajuste();
       this.compra = new Compra();
       this.fabricacion = new Fabricacion();
       this.setTitle("Saphiro - Movimientos de productos");
       //  crearHotKeys();
         actualizarTabla();
    }
    
    public boolean estacerrado(Object obj) {
        JInternalFrame[] activos = menuPrincipal.panel.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMovimiento = new javax.swing.JTable();
        txtMovimiento = new javax.swing.JTextField();
        btnCompra = new javax.swing.JButton();
        btnFabricacion = new javax.swing.JButton();
        btnAjuste = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(32, 182, 155));
        panelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtbMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbMovimiento);

        txtMovimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovimientoActionPerformed(evt);
            }
        });
        txtMovimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMovimientoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovimientoKeyReleased(evt);
            }
        });

        btnCompra.setBackground(new java.awt.Color(45, 178, 152));
        btnCompra.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra.setText("<html><font size=4><center>Compra<br>XX</center></font></html>");
        btnCompra.setBorder(null);
        btnCompra.setMaximumSize(new java.awt.Dimension(150, 45));
        btnCompra.setMinimumSize(new java.awt.Dimension(150, 45));
        btnCompra.setPreferredSize(new java.awt.Dimension(150, 45));
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnFabricacion.setBackground(new java.awt.Color(45, 178, 152));
        btnFabricacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnFabricacion.setForeground(new java.awt.Color(255, 255, 255));
        btnFabricacion.setText("<html><font size=4><center>Fabricación<br>XX</center></font></html>");
        btnFabricacion.setBorder(null);
        btnFabricacion.setMaximumSize(new java.awt.Dimension(150, 45));
        btnFabricacion.setMinimumSize(new java.awt.Dimension(1750, 45));
        btnFabricacion.setPreferredSize(new java.awt.Dimension(150, 45));
        btnFabricacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabricacionActionPerformed(evt);
            }
        });

        btnAjuste.setBackground(new java.awt.Color(45, 178, 152));
        btnAjuste.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnAjuste.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuste.setText("<html><font size=4><center>Ajúste<br>XX</center></font></html> ");
        btnAjuste.setBorder(null);
        btnAjuste.setMaximumSize(new java.awt.Dimension(150, 45));
        btnAjuste.setMinimumSize(new java.awt.Dimension(150, 45));
        btnAjuste.setPreferredSize(new java.awt.Dimension(150, 45));
        btnAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjusteActionPerformed(evt);
            }
        });

        btnReporte.setBackground(new java.awt.Color(45, 178, 152));
        btnReporte.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("<html><font size=4><center>Reporte<br>XX</center></font></html> ");
        btnReporte.setBorder(null);
        btnReporte.setMaximumSize(new java.awt.Dimension(150, 45));
        btnReporte.setMinimumSize(new java.awt.Dimension(150, 45));
        btnReporte.setPreferredSize(new java.awt.Dimension(150, 45));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 90, 125));
        jLabel1.setText("<html><font size=4><center>Búsqueda:<br></font></center></html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jLabel2.setBackground(new java.awt.Color(32, 182, 155));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/cuadro-700x400.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
     Compra();     
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnFabricacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabricacionActionPerformed
    Fabricacion();
    }//GEN-LAST:event_btnFabricacionActionPerformed

    private void btnAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjusteActionPerformed
      Ajuste();    
    }//GEN-LAST:event_btnAjusteActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
       Reporte();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void txtMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovimientoActionPerformed
        //
    }//GEN-LAST:event_txtMovimientoActionPerformed

    private void txtMovimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovimientoKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtbMovimiento.getRowCount() > 0) {
                jtbMovimiento.requestFocus();
                jtbMovimiento.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_txtMovimientoKeyPressed

    private void txtMovimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovimientoKeyReleased
        String filtro = txtMovimiento.getText();
        TableRowSorter sorter = new TableRowSorter(jtbMovimiento.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(filtro));
        jtbMovimiento.setRowSorter(sorter);
    }//GEN-LAST:event_txtMovimientoKeyReleased

    /**
     * @param args the command line arguments
     */
    public void creaHotKeys(){
    
        Action actCompra = new AbstractAction(Movimientos.Modulo.COMPRA.getAction()){
         @Override
            public void actionPerformed(ActionEvent e){
             Compra();
           }

       };
        
        Action actFabricacion = new AbstractAction(Movimientos.Modulo.FABRICACION.getAction()){
         @Override
            public void actionPerformed(ActionEvent e){
          Fabricacion();
           }

       };
        
        Action actAjuste = new AbstractAction(Movimientos.Modulo.AJUSTE.getAction()){
         @Override
            public void actionPerformed(ActionEvent e){
            Ajuste();
           }

       };
        
        Action actReporte = new AbstractAction(Movimientos.Modulo.REPORTE.getAction()){
         @Override
            public void actionPerformed(ActionEvent e){
             //Reporte();
           }

       };
    
       actCompra.putValue(Action.ACTION_COMMAND_KEY, KeyStroke.getKeyStroke(0,0));
       actFabricacion.putValue(Action.ACTION_COMMAND_KEY, KeyStroke.getKeyStroke(0,0));
       actAjuste.putValue(Action.ACTION_COMMAND_KEY, KeyStroke.getKeyStroke(0,0));
       actReporte.putValue(Action.ACTION_COMMAND_KEY, KeyStroke.getKeyStroke(0,0));
       
       
       btnCompra.getActionMap().put("actionCompra", actCompra);
       btnCompra.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke)actCompra.getValue(Action.ACCELERATOR_KEY), "actionCompra");
       
       btnFabricacion.getActionMap().put("acionFabricacion", actFabricacion);
       btnFabricacion.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actFabricacion.getValue(Action.ACCELERATOR_KEY), "actionFabricacion");
       
       btnAjuste.getActionMap().put("actionAjuste", actAjuste);
       btnAjuste.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actAjuste.getValue(Action.ACCELERATOR_KEY), "actionAjuste");
       
       btnReporte.getActionMap().put("actionReporte", actReporte);
       btnReporte.getInputMap().put((KeyStroke) actReporte.getValue(Action.ACCELERATOR_KEY), "actionReporte");
       
       
      
      InternalFrameAdapter listener = new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                menuPrincipal.requestFocus();
            }
        };

        this.addInternalFrameListener(listener);
      
    }
    public void actualizarTabla(){
        ArrayList<HashMap<String, String>> Movimiento = menuPrincipal.getOBD().getArrayListProductos();
       MovimientoTableModel model = new MovimientoTableModel(Movimiento);
        jtbMovimiento.setModel(model);
    }

    
    
    
    
    
    
    
      public Modulo getVentanaAbierta() {
        return ventanaAbierta;
    }

    
    public void setVentanaAbierta(Modulo ventanaAbierta) {
        this.ventanaAbierta = ventanaAbierta;
    }
    
  private enum Modulo {

        COMPRA(1, "actionCompra"),
       FABRICACION(2, "actionFabricacion"),
       AJUSTE(3, "actionAjuste"),
       REPORTE(4,"actionReporte");

        private final int id;
        private final String action;

        Modulo(int id, String action) {
            this.id = id;
            this.action = action;
        }

        public int getId() {
            return this.id;
        }

        private String getAction() {
            return this.action;
        }

    }
  
  
  public void Compra(){
      
    if(estacerrado(compra)){  
                compra = new Compra();
                Dimension desktopSize = menuPrincipal.panel.getSize();
                Dimension jInternalFrameSize = compra.getSize();
                compra.setLocation((desktopSize.width - jInternalFrameSize.width)/ 2,
                                   (desktopSize.height - jInternalFrameSize.height)/ 2);
                menuPrincipal.panel.add(compra);
                compra.show();
               setVentanaAbierta(Modulo.COMPRA);
                }else{
                   JOptionPane.showMessageDialog(this, "La ventana\n"+this.compra.getTitle()+ "\nse encuentra abierta...");
                  compra.toFront();
      }
  }
  
  public void Fabricacion(){
     
     if(estacerrado(fabricacion)) {
                fabricacion = new Fabricacion();
                Dimension desktopSize = menuPrincipal.panel.getSize();
                Dimension jInternalFrameSize = fabricacion.getSize();
                fabricacion.setLocation((desktopSize.width - jInternalFrameSize.width) /2,
                                        (desktopSize.height - jInternalFrameSize.height) /2);
                menuPrincipal.panel.add(fabricacion);
                fabricacion.show();
                setVentanaAbierta(Modulo.FABRICACION);
                }else{
                   JOptionPane.showMessageDialog(this, "La ventana\n"+this.fabricacion.getTitle()+"\nse encuentra abierta...");
                    fabricacion.toFront();
     }
  }
  
  public void Ajuste(){
      if(estacerrado(ajuste)){
                ajuste = new Ajuste();
                Dimension desktopSize = menuPrincipal.panel.getSize();
                Dimension jInternalFrameSize = ajuste.getSize();
                ajuste.setLocation((desktopSize.width - jInternalFrameSize.width) /2,
                                   (desktopSize.height -jInternalFrameSize.height)/2);
                menuPrincipal.panel.add(ajuste);
                ajuste.show();
                 setVentanaAbierta(Modulo.AJUSTE);
                }else{
                    JOptionPane.showMessageDialog(this, "La ventana\n"+this.ajuste.getTitle()+"\nse encuentra abierta...");
                     ajuste.toFront();
      }
  
  }
  
  
  public void Reporte(){
      if(estacerrado(reporte)){
                reporte = new Reporte();
                Dimension desktopSize = menuPrincipal.panel.getSize();
                Dimension jInternalFrameSize = reporte.getSize();
                reporte.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
                                    (desktopSize.height -jInternalFrameSize.height)/2);
                menuPrincipal.panel.add(reporte);
                reporte.show();
                setVentanaAbierta(Modulo.REPORTE);
                }else{
                    JOptionPane.showMessageDialog(this, "La ventana\n"+this.reporte.getTitle()+ "\nse encuentra abierta...");
                      reporte.toFront();
      }
  
  }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuste;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnFabricacion;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbMovimiento;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtMovimiento;
    // End of variables declaration//GEN-END:variables
}
