/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador.Ventanas;

import ClasesExtendidas.Tablas.ClienteTableModel;
import ClasesExtendidas.Tablas.EmpleadosTableModel;
import PuntoVenta.BaseDatos.Empleado;
import PuntoVenta.BaseDatos.Empresa;
import PuntoVenta.BaseDatos.ObjetoBaseDatos;
import PuntoVenta.BaseDatos.Pais;
import PuntoVenta.BaseDatos.Parametros;
import PuntoVenta.BaseDatos.PostgreSQL;
import PuntoVenta.Inicio.MenuPrincipal;
import PuntoVenta.Ventanas.Venta;
import PuntoVenta.fondo;
import Utilidades.currentLoger;
import Utilidades.ruta;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.prompt.*;

/**
 *
 * @author Inverdata
 */
public class Admin extends javax.swing.JInternalFrame {

    public final MenuPrincipal menuPrincipal;
    private static Admin admin;
    private Venta venta;
    //private final Object menuPrincipal;
    private ObjetoBaseDatos obd; //Objeto Base Datos
    private JTextField txtDocumento;
    private JComboBox cmbTipoDocumento;
    private JComboBox cmbCargoId;
    private RegistroEmpleados registroEmpleados;
    private ModificacionEmpleados modificacionEmpleados;
    private static String ruta = "";
    private RegistroCliente registroCliente;
    private RegistroCliente modificacionClientes;

    /**
     * Creates new form Admin
     * @param menuPrincipal
     */
    public Admin(MenuPrincipal menuPrincipal) {

        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.setTitle("Saphiro - Administración de Módulos");
        crearHotKeys();
        actualizarTabla();  
    }

    //OTRAS VENTANAS
    //UTILIZAR DESPUES PARA SISTEMA DE CAMBIO DE PANTALLAS
    //private MenuPrincipal.Modulo ventanaAbierta;
    //otros
    public fondo panel = new fondo();

    public void limpiar() {

        txtEmpresa.setText("");
        txtIdentificacion.setText("");
        txtMoneda.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");

        txtEmpresa.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelPrincipal = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListaCliente = new javax.swing.JTable();
        txtFiltro1 = new javax.swing.JTextField();
        agregarClientes = new javax.swing.JButton();
        modificarClientes = new javax.swing.JButton();
        eliminarClientes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        agregarEmpleados = new javax.swing.JButton();
        modificarEmpleados = new javax.swing.JButton();
        eliminarEmpleados = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListaEmpleado = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelParametros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToolBarAdmin = new javax.swing.JToolBar();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnParametros = new javax.swing.JButton();

        setBackground(new java.awt.Color(32, 182, 155));
        setClosable(true);
        setForeground(java.awt.Color.cyan);

        panelPrincipal.setBackground(new java.awt.Color(32, 182, 155));

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setLayout(new java.awt.CardLayout());

        panelClientes.setBackground(new java.awt.Color(32, 182, 155));

        jtbListaCliente.setBackground(new java.awt.Color(240, 240, 240));
        jtbListaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbListaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbListaClienteKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbListaCliente);

        txtFiltro1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltro1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltro1KeyReleased(evt);
            }
        });

        agregarClientes.setBackground(new java.awt.Color(32, 182, 155));
        agregarClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        agregarClientes.setForeground(new java.awt.Color(255, 255, 255));
        agregarClientes.setText("Agregar");
        agregarClientes.setBorder(null);
        agregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClientesActionPerformed(evt);
            }
        });

        modificarClientes.setBackground(new java.awt.Color(32, 182, 155));
        modificarClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        modificarClientes.setForeground(new java.awt.Color(255, 255, 255));
        modificarClientes.setText("Modificar");
        modificarClientes.setBorder(null);
        modificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClientesActionPerformed(evt);
            }
        });

        eliminarClientes.setBackground(new java.awt.Color(32, 182, 155));
        eliminarClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        eliminarClientes.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientes.setText("Eliminar");
        eliminarClientes.setBorder(null);
        eliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(28, 90, 125));
        jLabel8.setText("<html><font size=4><center>Búsqueda:<br></font></center></html>");

        jLabel10.setBackground(new java.awt.Color(32, 182, 155));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/cuadro-700x400.png"))); // NOI18N

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(agregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(modificarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(eliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientesLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientesLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        panelContenedor.add(panelClientes, "panelClientes");

        panelEmpleados.setBackground(new java.awt.Color(32, 182, 155));

        agregarEmpleados.setBackground(new java.awt.Color(32, 182, 155));
        agregarEmpleados.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        agregarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        agregarEmpleados.setText("Agregar");
        agregarEmpleados.setBorder(null);
        agregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadosActionPerformed(evt);
            }
        });

        modificarEmpleados.setBackground(new java.awt.Color(32, 182, 155));
        modificarEmpleados.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        modificarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        modificarEmpleados.setText("Modificar");
        modificarEmpleados.setBorder(null);
        modificarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpleadosActionPerformed(evt);
            }
        });

        eliminarEmpleados.setBackground(new java.awt.Color(32, 182, 155));
        eliminarEmpleados.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        eliminarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmpleados.setText("Eliminar");
        eliminarEmpleados.setBorder(null);
        eliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadosActionPerformed(evt);
            }
        });

        txtFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        jtbListaEmpleado.setBackground(new java.awt.Color(240, 240, 240));
        jtbListaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbListaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbListaEmpleadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListaEmpleado);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(28, 90, 125));
        jLabel7.setText("<html><font size=4><center>Búsqueda:<br></font></center></html>");

        jLabel11.setBackground(new java.awt.Color(32, 182, 155));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/cuadro-700x400.png"))); // NOI18N

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(agregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(modificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                    .addContainerGap(88, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        panelContenedor.add(panelEmpleados, "panelEmpleados");

        panelParametros.setBackground(new java.awt.Color(32, 182, 155));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 90, 125));
        jLabel1.setText("<html><font size=16><center>Parámetros:<br></font></center></html>");

        txtEmpresa.setEditable(false);
        txtEmpresa.setToolTipText("");
        txtEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtEmpresa.setFocusable(false);

        txtIdentificacion.setEditable(false);
        txtIdentificacion.setToolTipText("");
        txtIdentificacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtIdentificacion.setFocusable(false);

        txtTelefono.setEditable(false);
        txtTelefono.setToolTipText("");
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtTelefono.setFocusable(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 90, 125));
        jLabel2.setText("Empresa:");

        lblIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        lblIdentificacion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblIdentificacion.setForeground(new java.awt.Color(28, 90, 125));
        lblIdentificacion.setText("Rif:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 90, 125));
        jLabel4.setText("Dirección de Sede:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 90, 125));
        jLabel5.setText("Teléfono:");

        txtDireccion.setEditable(false);
        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        txtDireccion.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtDireccion);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(28, 90, 125));
        jLabel6.setText("Moneda:");

        txtMoneda.setEditable(false);
        txtMoneda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtMoneda.setFocusable(false);

        lblImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(28, 90, 125));
        jLabel9.setText("Logo:");

        txtPais.setEditable(false);
        txtPais.setToolTipText("");
        txtPais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        txtPais.setFocusable(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 90, 125));
        jLabel3.setText("Pais:");

        jLabel12.setBackground(new java.awt.Color(32, 182, 155));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/fondo-blanco-760x540.png"))); // NOI18N

        javax.swing.GroupLayout panelParametrosLayout = new javax.swing.GroupLayout(panelParametros);
        panelParametros.setLayout(panelParametrosLayout);
        panelParametrosLayout.setHorizontalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParametrosLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelParametrosLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panelParametrosLayout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelParametrosLayout.createSequentialGroup()
                                    .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIdentificacion)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelParametrosLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametrosLayout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelParametrosLayout.setVerticalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentificacion))
                .addGap(11, 11, 11)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelParametrosLayout.createSequentialGroup()
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelContenedor.add(panelParametros, "panelApariencia");

        jToolBarAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jToolBarAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 182, 155), 1, true));
        jToolBarAdmin.setFloatable(false);
        jToolBarAdmin.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarAdmin.setRollover(true);
        jToolBarAdmin.setBorderPainted(false);
        jToolBarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setFont(new java.awt.Font("SansSerif", 1, 8)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(28, 90, 125));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/7-empleados.png"))); // NOI18N
        btnEmpleados.setText("<html><font size=4><center>Empleados<br>F1</center></font></html>");
        btnEmpleados.setActionCommand("actionCaja");
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setSelected(true);
        btnEmpleados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
        });
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnEmpleados);

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("SansSerif", 1, 8)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(28, 90, 125));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/8-clientes.png"))); // NOI18N
        btnClientes.setText("<html><font size=4><center>Clientes<br>F2</center></font></html>");
        btnClientes.setActionCommand("actionVentas");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnClientes);

        btnParametros.setBackground(new java.awt.Color(255, 255, 255));
        btnParametros.setFont(new java.awt.Font("SansSerif", 1, 8)); // NOI18N
        btnParametros.setForeground(new java.awt.Color(28, 90, 125));
        btnParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/iconos p_v 24x24/9-parametros.png"))); // NOI18N
        btnParametros.setText("<html><font size=4><center>Parámetros<br>F3</center></font></html>");
        btnParametros.setFocusable(false);
        btnParametros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParametros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametrosActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnParametros);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 120, Short.MAX_VALUE)))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(815, Short.MAX_VALUE)
                    .addComponent(jToolBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jToolBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        empleados();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void empleados() {
        CardLayout card = (CardLayout) panelContenedor.getLayout();
        card.show(panelContenedor, "panelEmpleados");
        txtFiltro.requestFocus();
    }
    

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        clientes();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void clientes() {
        CardLayout card = (CardLayout) panelContenedor.getLayout();
        card.show(panelContenedor, "panelClientes");
        txtFiltro1.requestFocus();
    }

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String filtro = txtFiltro.getText();
        TableRowSorter sorter = new TableRowSorter(jtbListaEmpleado.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(filtro));
        jtbListaEmpleado.setRowSorter(sorter);
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtbListaEmpleado.getRowCount() > 0) {
                jtbListaEmpleado.requestFocus();
                jtbListaEmpleado.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_txtFiltroKeyPressed


    private void jtbListaEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbListaEmpleadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            //agregarEmpleado();
        }
    }//GEN-LAST:event_jtbListaEmpleadoKeyPressed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void jtbListaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbListaClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            //agregarCliente();
        }
    }//GEN-LAST:event_jtbListaClienteKeyPressed

    private void txtFiltro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltro1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtbListaCliente.getRowCount() > 0) {
                jtbListaCliente.requestFocus();
                jtbListaCliente.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_txtFiltro1KeyPressed

    private void txtFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltro1KeyReleased
        String filtro = txtFiltro1.getText();
        TableRowSorter sorter = new TableRowSorter(jtbListaCliente.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(filtro));
        jtbListaCliente.setRowSorter(sorter);
    }//GEN-LAST:event_txtFiltro1KeyReleased

    private void agregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadosActionPerformed
        abrirVentanaRegistroEmpleados();
    }//GEN-LAST:event_agregarEmpleadosActionPerformed

    private void modificarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpleadosActionPerformed
        modificarEmpleadoSeleccionado();
    }//GEN-LAST:event_modificarEmpleadosActionPerformed

    private void parametros() {
        Pais p = menuPrincipal.getOBD().getDatosPais(" WHERE activo = TRUE");
        
        Parametros para = menuPrincipal.getOBD().getDatosParametros();
        CardLayout card = (CardLayout) panelContenedor.getLayout();
        card.show(panelContenedor, "panelApariencia");
        //asignando datos a los campos
        txtPais.setText(para.getPais());
        txtEmpresa.setText(para.getNombre());
        lblIdentificacion.setText(p.getIdentificacion()+":");
        txtIdentificacion.setText(para.getIdentificacion());
        txtDireccion.setText(para.getDireccion());
        txtTelefono.setText(para.getTelefono());
        txtMoneda.setText(para.getMoneda());
        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg, para.getLogo());
        
        
//        PromptSupport.setBackground(Color.white, txtIdentificacion);
//        PromptSupport.setBackground(Color.white, txtDireccion);
//        PromptSupport.setBackground(Color.white, txtTelefono);
//        PromptSupport.setBackground(Color.white, txtMoneda);
//        txtEmpresa.requestFocus();
    }
    
    private void btnParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametrosActionPerformed
        parametros();
    }//GEN-LAST:event_btnParametrosActionPerformed

    private void eliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadosActionPerformed
        eliminarEmpleadoSeleccionado();
    }//GEN-LAST:event_eliminarEmpleadosActionPerformed

    private void agregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClientesActionPerformed
        abrirVentanaRegistroCliente();
    }//GEN-LAST:event_agregarClientesActionPerformed

    private void modificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClientesActionPerformed
        modificarClienteSeleccionado();
    }//GEN-LAST:event_modificarClientesActionPerformed

    private void eliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesActionPerformed
        eliminarClienteSeleccionado();
    }//GEN-LAST:event_eliminarClientesActionPerformed

//    public void mostrarAlerta() {
//        //Alerta.setVisible(true);
//    }

    public void actualizarTabla() {
        DefaultTableModel table = (DefaultTableModel)jtbListaEmpleado.getModel();
        DefaultTableModel table2 = (DefaultTableModel)jtbListaCliente.getModel();
        table.setNumRows(0);
        table2.setNumRows(0);
        
        ArrayList<HashMap<String, String>> listaEmpleados = menuPrincipal.getOBD().getArrayListEmpleado();
        EmpleadosTableModel model = new EmpleadosTableModel(listaEmpleados);
        jtbListaEmpleado.setModel(model);

        ArrayList<HashMap<String, String>> listaClientes = menuPrincipal.getOBD().getArrayListClientes();
        ClienteTableModel model2 = new ClienteTableModel(listaClientes);
        jtbListaCliente.setModel(model2);
    }

    private void abrirVentanaRegistroEmpleados() {
        registroEmpleados = new RegistroEmpleados(this);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = registroEmpleados.getSize();

        registroEmpleados.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(registroEmpleados);
        registroEmpleados.show();
    }

    public void abrirVentanaModificacionEmpleados(String tipo_persona, String numero_identificacion_persona) {
        modificacionEmpleados = new ModificacionEmpleados(this, tipo_persona, numero_identificacion_persona);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = modificacionEmpleados.getSize();
        modificacionEmpleados.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(modificacionEmpleados);
        modificacionEmpleados.show();
    }

    public void abrirVentanaRegistroCliente() {
        registroCliente = new RegistroCliente(this);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = registroCliente.getSize();
        registroCliente.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(registroCliente);
        registroCliente.show();
    }

    public void abrirVentanaModificacionCliente(String tipo_persona, String numero_identificacion_persona) {
        modificacionClientes = new RegistroCliente(this, tipo_persona, numero_identificacion_persona, true);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = modificacionClientes.getSize();
        modificacionClientes.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(modificacionClientes);
        modificacionClientes.show();
    }

    public static void conseguirRuta() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF & PNG Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(admin);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
//            System.out.println("You chose to open this file: "
//                    + chooser.getSelectedFile().getName());
        }
        
        txtEmpresa.setText(chooser.getSelectedFile().getAbsolutePath());
        String ruta = txtEmpresa.getText();
//        System.out.println(ruta);

    }

    public static String returnRuta() {

        return ruta;

    }

    private void focusPuntoInteres() {
        if (!this.txtFiltro.hasFocus()) {
            this.txtFiltro.requestFocus();
            this.txtFiltro.setSelectionStart(0);
            this.txtFiltro.setSelectionEnd(this.txtFiltro.getText().length());
        } else {
            txtFiltroKeyPressed(new KeyEvent(this, 0, 0, 0, KeyEvent.VK_ENTER, ' '));
        }
    }

    public ObjetoBaseDatos getOBD() {
        return obd;
    }

    public javax.swing.JTextField getTxtDocumento() {
        return txtDocumento;
    }

    public javax.swing.JComboBox getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public javax.swing.JComboBox getCmbTipoCargo() {
        return cmbCargoId;
    }

    /**
     * Método para eliminar un producto de la venta. Obtiene el idVenta de esta
     * misma clase.
     *
     */
    public void eliminarEmpleadoSeleccionado() {
        int numeroRow = jtbListaEmpleado.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaEmpleado.setRowSelectionInterval(0, 0);
            numeroRow = jtbListaEmpleado.getSelectedRow();
        }
        if (numeroRow >= 0) {
            
            int seleccion;
            seleccion = Utilidades.CuadroMensaje.getMensajeSiNo(this, "¿Desea eliminar el empleado " + jtbListaEmpleado.getModel().getValueAt(numeroRow, 1) + "?", "Eliminar empleado");
            if (seleccion == 0) {
                String identificacion = jtbListaEmpleado.getValueAt(numeroRow, 0).toString();
                String[] partes = identificacion.split("-");
                menuPrincipal.getOBD().eliminarEmpleado(partes[0], partes[1]);
                actualizarTabla();
                agregarEmpleados.setVisible(true);
                modificarEmpleados.setVisible(true);
                eliminarEmpleados.setText("Eliminar");

            } else {
                jtbListaEmpleado.requestFocus();
            }
        }
    }

    public void modificarEmpleadoSeleccionado() {
        int numeroRow = jtbListaEmpleado.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaEmpleado.setRowSelectionInterval(0, 0);
        }
        else {
            String identificacion = jtbListaEmpleado.getValueAt(numeroRow, 0).toString();
            String[] partes = identificacion.split("-");

            abrirVentanaModificacionEmpleados(partes[0], partes[1]);
        }
    }

    public void modificarClienteSeleccionado() {
        int numeroRow = jtbListaCliente.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaCliente.setRowSelectionInterval(0, 0);
        }
        else {
            String identificacion = jtbListaCliente.getValueAt(numeroRow, 0).toString();
            String[] partes = identificacion.split("-");
            
            abrirVentanaModificacionCliente(partes[0], partes[1]);
        }
    }

    public void eliminarClienteSeleccionado() {
        int numeroRow = jtbListaCliente.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaCliente.setRowSelectionInterval(0, 0);
            numeroRow = jtbListaCliente.getSelectedRow();
        }
        if (numeroRow >= 0) {
            int seleccion; 
            seleccion = Utilidades.CuadroMensaje.getMensajeSiNo(this, "¿Desea eliminar el cliente " + jtbListaCliente.getModel().getValueAt(numeroRow, 1) + "?", "Eliminar cliente");
            if (seleccion == 0) {
                String identificacion = jtbListaCliente.getValueAt(numeroRow, 0).toString();
                String[] partes = identificacion.split("-");
                menuPrincipal.getOBD().eliminarPersona(partes[0], partes[1]);
                actualizarTabla();
            } else {
                jtbListaCliente.requestFocus();
            }
        }
    }
    //Filtra a los empleados segun su estatus (activo o inactivo)
//    public void filtrarEmpleados(int indice) {
//        int index = cmbfiltrar.getSelectedIndex();
//        switch(indice){
//            case 1:
//                if(index == 0) {
//                    
//                }
//                else {
//                    actualizarTabla("0");
//                    agregarEmpleados.setVisible(false);
//                    modificarEmpleados.setVisible(false);
//                    eliminarEmpleados.setText("Recuperar");
//                }
//            break;
//            case 2: 
//                if(index == 0) {
//                    
//                }
//                else {
//                    eliminarEmpleadoSeleccionado("1");
//                }
//            break;
//        }  
//    }
    /*
    int numeroRow = jtbListaEmpleado.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaEmpleado.setRowSelectionInterval(0, 0);
            numeroRow = jtbListaEmpleado.getSelectedRow();
        }
        if (numeroRow >= 0) {
            int seleccion = Utilidades.CuadroMensaje.getMensajeSiNo(this, "¿Desea eliminar el empleado " + jtbListaEmpleado.getModel().getValueAt(numeroRow, 1) + "?", "Eliminar empleado");
            
            if (seleccion == 0) {
                String identificacion = jtbListaEmpleado.getValueAt(numeroRow, 0).toString();
                String[] partes = identificacion.split("-");
                menuPrincipal.getOBD().eliminarEmpleado(partes[0].charAt(0), partes[1]);
                actualizarTabla();

            } else {
                jtbListaEmpleado.requestFocus();
            }
        }*/

    /**
     * Método para crear y asignar HotKeys (accesos rápidos). Tiene 4 pasos: -
     * Crear el action que se activara cuando se pulse el boton.
     *
     * - Hacer un putValue(TipoKey, KeyStroke) a cada action.
     *
     * -Asignar el action al actionMap correspondiente de cada action. (método
     * getActionMap().put() en el elemento desde donde se activará el action).
     *
     * - Asignar el action al inputMap correspondiente de cada action. (método
     * getInputMap().put() en el elemento desde donde se activará el action).
     *
     * Para HotKeys dentro de tablas y otros elementos similares, debe asignarse
     * desde el listener keyTyped, keyPressed o keyReleased para que funcione.
     */
    private void crearHotKeys() {
        Action actCerrarVentana = new AbstractAction("actionCerrarVentanaCaja") {
            @Override
            public void actionPerformed(ActionEvent e) {
                cerrarVentana();
            }
        };
        Action actEmpleados = new AbstractAction(Admin.Modulo.EMPLEADOS.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                empleados();
            }
        };
        Action actClientes = new AbstractAction(Admin.Modulo.CLIENTES.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                clientes();
            }
        };
        Action actParametros = new AbstractAction(Admin.Modulo.PARAMETROS.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                parametros();
            }
        };

        actCerrarVentana.putValue(Action.ACTION_COMMAND_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_Q, ActionEvent.ALT_MASK));
        actEmpleados.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
        actClientes.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0));
        actParametros.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0));
        
        panelContenedor.getActionMap().put("actionCerrarVentanaCaja", actCerrarVentana);
        panelContenedor.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actCerrarVentana.getValue(Action.ACTION_COMMAND_KEY), "actionCerrarVentanaCaja");
        
        btnEmpleados.getActionMap().put(Admin.Modulo.EMPLEADOS.getAction(), actEmpleados);
        btnEmpleados.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actEmpleados.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.EMPLEADOS.getAction());

        btnClientes.getActionMap().put(Admin.Modulo.CLIENTES.getAction(), actClientes);
        btnClientes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actClientes.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.CLIENTES.getAction());

        btnParametros.getActionMap().put(Admin.Modulo.PARAMETROS.getAction(), actParametros);
        btnParametros.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actParametros.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.PARAMETROS.getAction());
    }

    private enum Modulo {

        EMPLEADOS(1, "actionEmpleados"),
        CLIENTES(2, "actionClientes"),
        PARAMETROS(3, "actionParametros");

        private final int id;
        private final String action;

        Modulo(int id, String action) {
            this.id = id;
            this.action = action;
        }

        public int getId() {
            return this.id;
        }

        private String getAction() {
            return this.action;
        }

    }

    private void cerrarVentana() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarClientes;
    private javax.swing.JButton agregarEmpleados;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnParametros;
    private javax.swing.JButton eliminarClientes;
    private javax.swing.JButton eliminarEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBarAdmin;
    public static javax.swing.JTable jtbListaCliente;
    public static javax.swing.JTable jtbListaEmpleado;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblImg;
    private javax.swing.JButton modificarClientes;
    private javax.swing.JButton modificarEmpleados;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelParametros;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea txtDireccion;
    public static javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtFiltro1;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtMoneda;
    public static javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
