/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador.Ventanas;

import ClasesExtendidas.Tablas.ClienteTableModel;
import ClasesExtendidas.Tablas.EmpleadosTableModel;
import PuntoVenta.BaseDatos.Empresa;
import PuntoVenta.BaseDatos.ObjetoBaseDatos;
import PuntoVenta.Inicio.MenuPrincipal;
import PuntoVenta.Ventanas.Venta;
import PuntoVenta.fondo;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.prompt.*;

/**
 *
 * @author Inverdata
 */
public class Admin extends javax.swing.JInternalFrame {

    public final MenuPrincipal menuPrincipal;
    private static Admin admin;
    private Venta venta;
    //private final Object menuPrincipal;
    private ObjetoBaseDatos obd; //Objeto Base Datos
    private JTextField txtDocumento;
    private JComboBox cmbTipoDocumento;
    private JComboBox cmbCargoId;
    private RegistroEmpleados registroEmpleados;
    private ModificacionEmpleados modificacionEmpleados;
    private static String ruta = "";
    private RegistroCliente registroCliente;
    private RegistroCliente modificacionClientes;

    /**
     * Creates new form Admin
     * @param menuPrincipal
     */
    public Admin(MenuPrincipal menuPrincipal) {

        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.setTitle("Saphiro - Administración de Módulos");
        crearHotKeys();
        actualizarTabla();
    }

    //OTRAS VENTANAS
    //UTILIZAR DESPUES PARA SISTEMA DE CAMBIO DE PANTALLAS
    //private MenuPrincipal.Modulo ventanaAbierta;
    //otros
    public fondo panel = new fondo();

    public void limpiar() {

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");

        jTextField1.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarAdmin = new javax.swing.JToolBar();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnParametros = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        panelEmpleados = new javax.swing.JPanel();
        agregarEmpleados = new javax.swing.JButton();
        modificarEmpleados = new javax.swing.JButton();
        eliminarEmpleados = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListaEmpleado = new javax.swing.JTable();
        panelClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListaCliente = new javax.swing.JTable();
        txtFiltro1 = new javax.swing.JTextField();
        agregarClientes = new javax.swing.JButton();
        modificarClientes = new javax.swing.JButton();
        eliminarClientes = new javax.swing.JButton();
        panelParametros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Alerta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(32, 182, 155));
        setClosable(true);
        setForeground(java.awt.Color.cyan);

        jToolBarAdmin.setBackground(new java.awt.Color(32, 182, 155));
        jToolBarAdmin.setFloatable(false);
        jToolBarAdmin.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarAdmin.setRollover(true);
        jToolBarAdmin.setBorderPainted(false);
        jToolBarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEmpleados.setBackground(new java.awt.Color(32, 182, 155));
        btnEmpleados.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/01. empleados.png"))); // NOI18N
        btnEmpleados.setText("<html><font size=2><center>Empleados<br>F1</center></font></html>");
        btnEmpleados.setActionCommand("actionCaja");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setSelected(true);
        btnEmpleados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseEntered(evt);
            }
        });
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnEmpleados);

        btnClientes.setBackground(new java.awt.Color(32, 182, 155));
        btnClientes.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/01. clientes.png"))); // NOI18N
        btnClientes.setText("<html><font size=2><center>Clientes<br>F2</center></font></html>");
        btnClientes.setActionCommand("actionVentas");
        btnClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClientes.setBorderPainted(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnClientes);

        btnParametros.setBackground(new java.awt.Color(32, 182, 155));
        btnParametros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnParametros.setForeground(new java.awt.Color(0, 0, 0));
        btnParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuntoVenta/Iconos/01.parametros.png"))); // NOI18N
        btnParametros.setText("<html><font size=2><center>Parámetros<br>F3</center></font></html>");
        btnParametros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnParametros.setBorderPainted(false);
        btnParametros.setFocusable(false);
        btnParametros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParametros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametrosActionPerformed(evt);
            }
        });
        jToolBarAdmin.add(btnParametros);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelEmpleados.setBackground(new java.awt.Color(32, 182, 155));

        agregarEmpleados.setText("Agregar");
        agregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadosActionPerformed(evt);
            }
        });

        modificarEmpleados.setText("Modificar");
        modificarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpleadosActionPerformed(evt);
            }
        });

        eliminarEmpleados.setText("Eliminar");
        eliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadosActionPerformed(evt);
            }
        });

        txtFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        jtbListaEmpleado.setBackground(new java.awt.Color(240, 240, 240));
        jtbListaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbListaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbListaEmpleadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListaEmpleado);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                .addComponent(agregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(modificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(195, 195, 195))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelEmpleados, "panelEmpleados");

        panelClientes.setBackground(new java.awt.Color(32, 182, 155));

        jtbListaCliente.setBackground(new java.awt.Color(240, 240, 240));
        jtbListaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbListaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbListaClienteKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbListaCliente);

        txtFiltro1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltro1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltro1KeyReleased(evt);
            }
        });

        agregarClientes.setText("Agregar");
        agregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClientesActionPerformed(evt);
            }
        });

        modificarClientes.setText("Modificar");
        modificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClientesActionPerformed(evt);
            }
        });

        eliminarClientes.setText("Eliminar");
        eliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(agregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(modificarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(txtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelClientes, "panelClientes");

        panelParametros.setBackground(new java.awt.Color(32, 182, 155));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Parámetros");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.setToolTipText("");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField4.setToolTipText("");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Rif:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Dirección de Sede:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Teléfono:");

        Alerta.setVisible(false);
        Alerta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Alerta.setForeground(new java.awt.Color(255, 0, 0));
        Alerta.setText("Ej: ####-#######");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea1);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Moneda:");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelParametrosLayout = new javax.swing.GroupLayout(panelParametros);
        panelParametros.setLayout(panelParametrosLayout);
        panelParametrosLayout.setHorizontalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametrosLayout.createSequentialGroup()
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Alerta)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)
                            .addComponent(jScrollPane3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                        .addGap(150, 150, 150))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        panelParametrosLayout.setVerticalGroup(
            panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametrosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95))
                    .addGroup(panelParametrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Alerta)
                .addGap(16, 16, 16)
                .addGroup(panelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
        );

        panelPrincipal.add(panelParametros, "panelApariencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        empleados();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void empleados() {
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "panelEmpleados");
        txtFiltro.requestFocus();
    }

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        clientes();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void clientes() {
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "panelClientes");
        txtFiltro1.requestFocus();
    }

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String filtro = txtFiltro.getText();
        TableRowSorter sorter = new TableRowSorter(jtbListaEmpleado.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(filtro));
        jtbListaEmpleado.setRowSorter(sorter);
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtbListaEmpleado.getRowCount() > 0) {
                jtbListaEmpleado.requestFocus();
                jtbListaEmpleado.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_txtFiltroKeyPressed


    private void jtbListaEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbListaEmpleadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            //agregarEmpleado();
        }
    }//GEN-LAST:event_jtbListaEmpleadoKeyPressed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void jtbListaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbListaClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            //agregarCliente();
        }
    }//GEN-LAST:event_jtbListaClienteKeyPressed

    private void txtFiltro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltro1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtbListaCliente.getRowCount() > 0) {
                jtbListaCliente.requestFocus();
                jtbListaCliente.setRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_txtFiltro1KeyPressed

    private void txtFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltro1KeyReleased
        String filtro = txtFiltro1.getText();
        TableRowSorter sorter = new TableRowSorter(jtbListaCliente.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(filtro));
        jtbListaCliente.setRowSorter(sorter);
    }//GEN-LAST:event_txtFiltro1KeyReleased

    private void agregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadosActionPerformed
        abrirVentanaRegistroEmpleados();
    }//GEN-LAST:event_agregarEmpleadosActionPerformed

    private void modificarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpleadosActionPerformed
        modificarEmpleadoSeleccionado();
    }//GEN-LAST:event_modificarEmpleadosActionPerformed

    private void parametros() {
        Empresa emp = menuPrincipal.getOBD().datosEmpresas();
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "panelApariencia");
        if (emp == null) {
            PromptSupport.setPrompt("Nombre de la Empresa", jTextField1);
            PromptSupport.setPrompt("J-12345678-9", jTextField2);
            PromptSupport.setPrompt("Dirección", jTextArea1);
            PromptSupport.setPrompt("####-#######", jTextField4);
            PromptSupport.setPrompt("Ej: Bs, $, €", jTextField3);
        } else {
            jTextField1.setText(emp.getNombre());
            jTextField2.setText(emp.getRif());
            jTextArea1.setText(emp.getDireccion());
            jTextField4.setText(emp.getTelefono());
            jTextField3.setText(emp.getMoneda());
        }
        PromptSupport.setBackground(Color.white, jTextField2);
        PromptSupport.setBackground(Color.white, jTextArea1);
        PromptSupport.setBackground(Color.white, jTextField4);
        PromptSupport.setBackground(Color.white, jTextField3);
        jTextField1.requestFocus();
        habilitar();
    }

    private void btnParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametrosActionPerformed
        parametros();
    }//GEN-LAST:event_btnParametrosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nombre = jTextField1.getText();
        String rif = jTextField2.getText();
        String direccion = jTextArea1.getText();
        String telefono = jTextField4.getText();
        String moneda = jTextField3.getText();

        if ((nombre.trim().equals("") || rif.trim().equals("") || direccion.trim().equals("") || telefono.trim().equals("") || moneda.trim().equals("")) || (telefono.length() < 12)) {
            Utilidades.Sonidos.beep();
            JOptionPane.showMessageDialog(null, "Documentos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } else {
            /*menuPrincipal.getOBD().ingresoEmp(nombre, rif, telefono, direccion, moneda);
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            limpiar();*/
        }

        //abrirVentanaUpload();
        //conseguirRuta();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadosActionPerformed
        eliminarEmpleadoSeleccionado();
    }//GEN-LAST:event_eliminarEmpleadosActionPerformed

    private void agregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClientesActionPerformed
        abrirVentanaRegistroCliente();
    }//GEN-LAST:event_agregarClientesActionPerformed

    private void modificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClientesActionPerformed
        modificarClienteSeleccionado();
    }//GEN-LAST:event_modificarClientesActionPerformed

    private void eliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesActionPerformed
        eliminarClienteSeleccionado();
    }//GEN-LAST:event_eliminarClientesActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        jTextField1.setBackground(Color.white);
    }//GEN-LAST:event_jTextField1KeyPressed
    private void habilitar() {
        if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty()) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }

    public void mostrarAlerta() {
        Alerta.setVisible(true);
    }

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        boolean valido = true;
        if ((!Character.isDigit(evt.getKeyChar()) && (evt.getKeyChar() != KeyEvent.VK_MINUS))) {
            evt.consume();
        } else if ((Character.isDigit(evt.getKeyChar())) && jTextField4.getText().length() == 4) {
            evt.consume();
        } else if (jTextField4.getText().length() != 4 && (evt.getKeyChar() == KeyEvent.VK_MINUS)) {
            evt.consume();
        } else if (jTextField4.getText().length() > 11) {
            evt.consume();
        } else {
            valido = false;
        }
        if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
            valido = false;
        }
        if (jTextField4.getText().length() == 12) {
            valido = false;
        }
        Alerta.setVisible(valido);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        if (jTextField1.getText().length() > 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        if (!jTextArea1.getText().isEmpty() && jTextArea1.getText().length() % 38 == 0) {
            jTextArea1.setText(jTextArea1.getText() + "\n");
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        if (jTextField2.getText().length() > 11) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    public void actualizarTabla() {
        ArrayList<HashMap<String, String>> listaEmpleados = menuPrincipal.getOBD().getArrayListEmpleado();
        EmpleadosTableModel model = new EmpleadosTableModel(listaEmpleados);
        jtbListaEmpleado.setModel(model);

        ArrayList<HashMap<String, String>> listaClientes = menuPrincipal.getOBD().getArrayListClientes();
        ClienteTableModel model2 = new ClienteTableModel(listaClientes);
        jtbListaCliente.setModel(model2);
    }

    private void abrirVentanaRegistroEmpleados() {
        registroEmpleados = new RegistroEmpleados(this);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = registroEmpleados.getSize();

        registroEmpleados.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(registroEmpleados);
        registroEmpleados.show();
    }

    public void abrirVentanaModificacionEmpleados(char tipo_persona, String numero_identificacion_persona) {
        modificacionEmpleados = new ModificacionEmpleados(this, tipo_persona, numero_identificacion_persona);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = modificacionEmpleados.getSize();
        modificacionEmpleados.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(modificacionEmpleados);
        modificacionEmpleados.show();
    }

    public void abrirVentanaRegistroCliente() {
        registroCliente = new RegistroCliente(this);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = registroCliente.getSize();
        registroCliente.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(registroCliente);
        registroCliente.show();
    }

    public void abrirVentanaModificacionCliente(char tipo_persona, String numero_identificacion_persona) {
        modificacionClientes = new RegistroCliente(this, tipo_persona, numero_identificacion_persona, true);
        Dimension desktopSize = menuPrincipal.panel.getSize();
        Dimension jInternalFrameSize = modificacionClientes.getSize();
        modificacionClientes.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        menuPrincipal.panel.add(modificacionClientes);
        modificacionClientes.show();
    }

    public static void conseguirRuta() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF & PNG Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(admin);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
//            System.out.println("You chose to open this file: "
//                    + chooser.getSelectedFile().getName());
        }

        jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
        String ruta = jTextField1.getText();
//        System.out.println(ruta);

    }

    public static String returnRuta() {

        return ruta;

    }

    private void focusPuntoInteres() {
        if (!this.txtFiltro.hasFocus()) {
            this.txtFiltro.requestFocus();
            this.txtFiltro.setSelectionStart(0);
            this.txtFiltro.setSelectionEnd(this.txtFiltro.getText().length());
        } else {
            txtFiltroKeyPressed(new KeyEvent(this, 0, 0, 0, KeyEvent.VK_ENTER, ' '));
        }
    }

    public ObjetoBaseDatos getOBD() {
        return obd;
    }

    public javax.swing.JTextField getTxtDocumento() {
        return txtDocumento;
    }

    public javax.swing.JComboBox getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public javax.swing.JComboBox getCmbTipoCargo() {
        return cmbCargoId;
    }

    /**
     * Método para eliminar un producto de la venta. Obtiene el idVenta de esta
     * misma clase.
     *
     */
    public void eliminarEmpleadoSeleccionado() {
        int numeroRow = jtbListaEmpleado.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaEmpleado.setRowSelectionInterval(0, 0);
            numeroRow = jtbListaEmpleado.getSelectedRow();
        }
        if (numeroRow >= 0) {
            int seleccion = Utilidades.CuadroMensaje.getMensajeSiNo(this, "¿Desea eliminar el empleado " + jtbListaEmpleado.getModel().getValueAt(numeroRow, 1) + "?", "Eliminar empleado");
            
            if (seleccion == 0) {
                String identificacion = jtbListaEmpleado.getValueAt(numeroRow, 0).toString();
                String[] partes = identificacion.split("-");
                menuPrincipal.getOBD().eliminarEmpleado(partes[0].charAt(0), partes[1]);
                actualizarTabla();

            } else {
                jtbListaEmpleado.requestFocus();
            }
        }
    }

    public void modificarEmpleadoSeleccionado() {
        int numeroRow = jtbListaEmpleado.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaEmpleado.setRowSelectionInterval(0, 0);
        }
        else {
            String identificacion = jtbListaEmpleado.getValueAt(numeroRow, 0).toString();
            String[] partes = identificacion.split("-");

            abrirVentanaModificacionEmpleados(partes[0].charAt(0), partes[1]);
        }
    }

    public void modificarClienteSeleccionado() {
        int numeroRow = jtbListaCliente.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaCliente.setRowSelectionInterval(0, 0);
        }
        else {
            String identificacion = jtbListaCliente.getValueAt(numeroRow, 0).toString();
            String[] partes = identificacion.split("-");
            
            abrirVentanaModificacionCliente(partes[0].charAt(0), partes[1]);
        }
    }

    public void eliminarClienteSeleccionado() {
        int numeroRow = jtbListaCliente.getSelectedRow();
        if (numeroRow < 0) {
            jtbListaCliente.setRowSelectionInterval(0, 0);
            numeroRow = jtbListaCliente.getSelectedRow();
        }
        if (numeroRow >= 0) {
            int seleccion = Utilidades.CuadroMensaje.getMensajeSiNo(this, "¿Desea eliminar el cliente " + jtbListaCliente.getModel().getValueAt(numeroRow, 1) + "?", "Eliminar cliente");
            if (seleccion == 0) {
                String identificacion = jtbListaCliente.getValueAt(numeroRow, 0).toString();
                String[] partes = identificacion.split("-");
                menuPrincipal.getOBD().eliminarPersona(partes[0].charAt(0), partes[1]);
                actualizarTabla();

            } else {
                jtbListaCliente.requestFocus();
            }
        }
    }

    /**
     * Método para crear y asignar HotKeys (accesos rápidos). Tiene 4 pasos: -
     * Crear el action que se activara cuando se pulse el boton.
     *
     * - Hacer un putValue(TipoKey, KeyStroke) a cada action.
     *
     * -Asignar el action al actionMap correspondiente de cada action. (método
     * getActionMap().put() en el elemento desde donde se activará el action).
     *
     * - Asignar el action al inputMap correspondiente de cada action. (método
     * getInputMap().put() en el elemento desde donde se activará el action).
     *
     * Para HotKeys dentro de tablas y otros elementos similares, debe asignarse
     * desde el listener keyTyped, keyPressed o keyReleased para que funcione.
     */
    private void crearHotKeys() {
        Action actEmpleados = new AbstractAction(Admin.Modulo.EMPLEADOS.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                empleados();
            }
        };
        Action actClientes = new AbstractAction(Admin.Modulo.CLIENTES.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                clientes();
            }
        };
        Action actParametros = new AbstractAction(Admin.Modulo.PARAMETROS.getAction()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                parametros();
            }
        };

        actEmpleados.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
        actClientes.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0));
        actParametros.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0));

        btnEmpleados.getActionMap().put(Admin.Modulo.EMPLEADOS.getAction(), actEmpleados);
        btnEmpleados.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actEmpleados.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.EMPLEADOS.getAction());

        btnClientes.getActionMap().put(Admin.Modulo.CLIENTES.getAction(), actClientes);
        btnClientes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actClientes.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.CLIENTES.getAction());

        btnParametros.getActionMap().put(Admin.Modulo.PARAMETROS.getAction(), actParametros);
        btnParametros.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put((KeyStroke) actParametros.getValue(Action.ACCELERATOR_KEY), Admin.Modulo.PARAMETROS.getAction());
    }

    private enum Modulo {

        EMPLEADOS(1, "actionEmpleados"),
        CLIENTES(2, "actionClientes"),
        PARAMETROS(3, "actionParametros");

        private final int id;
        private final String action;

        Modulo(int id, String action) {
            this.id = id;
            this.action = action;
        }

        public int getId() {
            return this.id;
        }

        private String getAction() {
            return this.action;
        }

    }

    /*private void cerrarVentana() {
        this.dispose();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    private javax.swing.JButton agregarClientes;
    private javax.swing.JButton agregarEmpleados;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnParametros;
    private javax.swing.JButton eliminarClientes;
    private javax.swing.JButton eliminarEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBarAdmin;
    private javax.swing.JTable jtbListaCliente;
    public static javax.swing.JTable jtbListaEmpleado;
    private javax.swing.JButton modificarClientes;
    private javax.swing.JButton modificarEmpleados;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelParametros;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtFiltro1;
    // End of variables declaration//GEN-END:variables

}
