-- MySQL Script generated by MySQL Workbench
-- mar 20 feb 2018 10:20:23 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paydesk_closing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk_closing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk_closing` (
  `id_paydesk_closing` INT NOT NULL,
  `physical_amount` VARCHAR(45) NULL,
  `system_amount` VARCHAR(45) NULL,
  `employee` VARCHAR(45) NULL,
  `closing_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paydesk_closing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paydesk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk` (
  `id_paydesk` INT NOT NULL,
  `paydesk_description` VARCHAR(30) NULL,
  PRIMARY KEY (`id_paydesk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`charge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`charge` ;

CREATE TABLE IF NOT EXISTS `mydb`.`charge` (
  `id_charge` INT NOT NULL,
  `charge_description` VARCHAR(30) NULL,
  `system_access` TINYINT(1) NULL,
  PRIMARY KEY (`id_charge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id_employee` INT NOT NULL,
  `employee_fisrt_name` VARCHAR(30) NULL,
  `employee_last_name` VARCHAR(30) NULL,
  `employee_nationality` VARCHAR(1) NULL,
  `employee_id_number` VARCHAR(10) NULL,
  `employee_email` VARCHAR(45) NULL,
  `employee_phone` VARCHAR(11) NULL,
  `password` VARCHAR(100) NULL,
  `departament` VARCHAR(45) NULL,
  `charge_id_charge` INT NOT NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `fk_employee_charge1_idx` (`charge_id_charge` ASC),
  CONSTRAINT `fk_employee_charge1`
    FOREIGN KEY (`charge_id_charge`)
    REFERENCES `mydb`.`charge` (`id_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paydesk_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk_status` (
  `id_paydesk_status` INT NOT NULL,
  `paydesk_opening_date` VARCHAR(45) NULL,
  `paydesk_closing_date` VARCHAR(45) NULL,
  `opening_amount` DECIMAL(10,0) NULL,
  `closing_amount` DECIMAL(10,0) NULL,
  `paydesk_status_excess` DECIMAL(10,0) NULL,
  `paydesk_id_paydesk` INT NOT NULL,
  `employee_id_employee` INT NOT NULL,
  PRIMARY KEY (`id_paydesk_status`),
  INDEX `fk_paydesk_status_paydesk1_idx` (`paydesk_id_paydesk` ASC),
  INDEX `fk_paydesk_status_employee1_idx` (`employee_id_employee` ASC),
  CONSTRAINT `fk_paydesk_status_paydesk1`
    FOREIGN KEY (`paydesk_id_paydesk`)
    REFERENCES `mydb`.`paydesk` (`id_paydesk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paydesk_status_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `mydb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paydesk_cut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk_cut` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk_cut` (
  `id_paydesk_cut` INT NOT NULL,
  `cut_amount` DECIMAL(10,0) NULL,
  `paydesk_date_hour` VARCHAR(45) NULL,
  `excess` VARCHAR(45) NULL,
  `remaining` VARCHAR(45) NULL,
  `closed` VARCHAR(45) NULL,
  `paydesk_status_id_paydesk_status` INT NOT NULL,
  PRIMARY KEY (`id_paydesk_cut`),
  INDEX `fk_paydesk_cut_paydesk_status1_idx` (`paydesk_status_id_paydesk_status` ASC),
  CONSTRAINT `fk_paydesk_cut_paydesk_status1`
    FOREIGN KEY (`paydesk_status_id_paydesk_status`)
    REFERENCES `mydb`.`paydesk_status` (`id_paydesk_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paydesk_breakdown`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk_breakdown` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk_breakdown` (
  `id_paydesk_breakdown` INT NOT NULL,
  `breakdown_amount` DECIMAL(10,0) NULL,
  `paydesk_pay_type` VARCHAR(45) NULL,
  `payment_type_breakdown` VARCHAR(45) NULL,
  `paydesk_cut_id_paydesk_cut` INT NOT NULL,
  PRIMARY KEY (`id_paydesk_breakdown`),
  INDEX `fk_paydesk_breakdown_paydesk_cut_idx` (`paydesk_cut_id_paydesk_cut` ASC),
  CONSTRAINT `fk_paydesk_breakdown_paydesk_cut`
    FOREIGN KEY (`paydesk_cut_id_paydesk_cut`)
    REFERENCES `mydb`.`paydesk_cut` (`id_paydesk_cut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`system_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`system_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`system_user` (
  `id_system_user` INT NOT NULL,
  `system_user_password` VARCHAR(128) NULL,
  `last_login` VARCHAR(45) NULL,
  `system_user_email` VARCHAR(75) NULL,
  `active` TINYINT(1) NULL,
  `admin` TINYINT(1) NULL,
  `staff` TINYINT(1) NULL,
  PRIMARY KEY (`id_system_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id_customer` INT NOT NULL,
  `customer_name` VARCHAR(30) NULL,
  `customer_first_name` VARCHAR(30) NULL,
  `customer_last_name` VARCHAR(45) NULL,
  `customer_address` VARCHAR(120) NULL,
  `customer_nationality` VARCHAR(1) NULL,
  `customer_id_number` VARCHAR(10) NULL,
  `customer_phone` VARCHAR(11) NULL,
  `customer_email` VARCHAR(75) NULL,
  `gender` VARCHAR(1) NULL,
  `twitter` VARCHAR(30) NULL,
  `facebook` VARCHAR(30) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sale_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sale_status` (
  `id_sale_status` INT NOT NULL,
  `sale_status_descrption` VARCHAR(30) NULL,
  PRIMARY KEY (`id_sale_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `id_sale` INT NOT NULL,
  `sale_tax` VARCHAR(45) NULL,
  `sale_total` VARCHAR(45) NULL,
  `sale_bill_code` INT(11) NULL,
  `sale_date_time` VARCHAR(45) NULL,
  `non_exempt_total` VARCHAR(45) NULL,
  `exempt_total` VARCHAR(45) NULL,
  `totalpag` VARCHAR(45) NULL,
  `change` VARCHAR(45) NULL,
  `paydesk_sale_cut` TINYINT(1) NULL,
  `paydesk_sale_closing` TINYINT(1) NULL,
  `paydesk_status_id_paydesk_status` INT NOT NULL,
  `employee_id_employee` INT NOT NULL,
  `client_id_client` INT NOT NULL,
  `sale_status_id_sale_status` INT NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `fk_sales_paydesk_status1_idx` (`paydesk_status_id_paydesk_status` ASC),
  INDEX `fk_sales_employee1_idx` (`employee_id_employee` ASC),
  INDEX `fk_sales_client1_idx` (`client_id_client` ASC),
  INDEX `fk_sales_sale_status1_idx` (`sale_status_id_sale_status` ASC),
  CONSTRAINT `fk_sales_paydesk_status1`
    FOREIGN KEY (`paydesk_status_id_paydesk_status`)
    REFERENCES `mydb`.`paydesk_status` (`id_paydesk_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `mydb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_sale_status1`
    FOREIGN KEY (`sale_status_id_sale_status`)
    REFERENCES `mydb`.`sale_status` (`id_sale_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_balance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_balance` (
  `id_item_balance` INT NOT NULL,
  `bar_code` VARCHAR(40) NULL,
  `item_description` VARCHAR(50) NULL,
  `min_stock` DECIMAL(10,0) NULL,
  `max_stock` DECIMAL(10,0) NULL,
  `client_limit_sale` DECIMAL(10,0) NULL,
  `point_of_order` DECIMAL(10,0) NULL,
  `unit_cost` DECIMAL(10,0) NULL,
  `profit_margin` DECIMAL(10,0) NULL,
  `taxable_base` DECIMAL(10,0) NULL,
  `balance_update_date` DATE NULL,
  `tax` DECIMAL(10,0) NULL,
  `cost` DECIMAL(10,0) NULL,
  `boxing_description` VARCHAR(45) NULL,
  `item_quantity` DECIMAL(10,0) NULL,
  `scale` REAL NULL,
  `scale_unit` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_balance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_sale` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_sale` (
  `id_item_sale` INT NOT NULL,
  `item_sale_quantity` DECIMAL(10,0) NULL,
  `sales_id_sale` INT NOT NULL,
  `item_balance_id_item_balance` INT NOT NULL,
  PRIMARY KEY (`id_item_sale`),
  INDEX `fk_item_sale_sales1_idx` (`sales_id_sale` ASC),
  INDEX `fk_item_sale_item_balance1_idx` (`item_balance_id_item_balance` ASC),
  CONSTRAINT `fk_item_sale_sales1`
    FOREIGN KEY (`sales_id_sale`)
    REFERENCES `mydb`.`sales` (`id_sale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_sale_item_balance1`
    FOREIGN KEY (`item_balance_id_item_balance`)
    REFERENCES `mydb`.`item_balance` (`id_item_balance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id_payment` INT NOT NULL,
  `payment_type` VARCHAR(45) NULL,
  `payment_amount` VARCHAR(45) NULL,
  `payment_date_time` VARCHAR(45) NULL,
  `sales_id_sale` INT NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `fk_payment_sales1_idx` (`sales_id_sale` ASC),
  CONSTRAINT `fk_payment_sales1`
    FOREIGN KEY (`sales_id_sale`)
    REFERENCES `mydb`.`sales` (`id_sale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`currency_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`currency_type` (
  `id_currency_type` INT NOT NULL,
  `currency_type_description` VARCHAR(20) NULL,
  PRIMARY KEY (`id_currency_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`currency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `id_currency` INT NOT NULL,
  `currency_value` DECIMAL(10,0) NULL,
  `currency_description` VARCHAR(30) NULL,
  `currency_type_id_currency_type` INT NOT NULL,
  PRIMARY KEY (`id_currency`),
  INDEX `fk_currency_currency_type1_idx` (`currency_type_id_currency_type` ASC),
  CONSTRAINT `fk_currency_currency_type1`
    FOREIGN KEY (`currency_type_id_currency_type`)
    REFERENCES `mydb`.`currency_type` (`id_currency_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id_company` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `company_rif` VARCHAR(45) NULL,
  `company_phone` VARCHAR(45) NULL,
  `company_address` VARCHAR(45) NULL,
  `used_currency` VARCHAR(45) NULL,
  PRIMARY KEY (`id_company`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
